import { Flavor } from './Flavor'

import path from 'path'

export const T1: Flavor = {
  name: 'Bubble Gum',
  meta: {
    description:
      'This image and animation heavy template allows enough space to highlight multiple details about the job.',
    orientation: '16:9',
    duration: 40,
    imageUrl:
      'https://res.cloudinary.com/hdngr/image/upload/v1647965385/thumbnails/1759.jpg',
    vimeoId: '690707002',
    category: 'Job Postings',
  },
  template: {
    src: `file://${path.join(__dirname, '../../render-templates/T1.aep')}`,
    composition: 'Main',
    outputExt: 'mov',
  },
  layers: {
    soundTrack: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Soundtrack',
    },
    brandColor1: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for titles and the main text on a slide.',
      scriptVariable: 'Brand Color (Contrast with background & button text)',
    },
    brandColor2: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Background color for slides.',
      scriptVariable: 'Background Color',
      value: '#ffffff',
    },
    brandColor3: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description:
        'Used for sub titles and secondary text on a slide (hint: can be the same as any of the other colors if you want!).',
      scriptVariable: 'Main Text (slide content)',
    },
    brandColor4: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for titles with backgrounds and call to action text.',
      scriptVariable: 'Button & Contrast Text (Over Brand Color)',
      value: '#ffffff',
    },
    logo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Logo',
    },
    iconOne: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Location Icon',
      id: '220',
    },
    iconTwo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Bullet Icon',
      id: '204',
    },
    backgroundImageOne: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Under Job Title Banner',
      slideType: 'middle-row',
    },
    backgroundImageTwo: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Left 50%',
      slideType: 'left50-gradient',
    },
    backgroundImageThree: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Left 50%',
      slideType: 'left50-gradient',
    },
    backgroundImageFour: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Left 50%',
      slideType: 'left50-gradient',
    },
    backgroundImageFive: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Left 50%',
      slideType: 'left50-testimonial',
    },
    tagLine: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 20,
      scriptVariable: 'Hiring: (Tagline)',
      value: 'Now Hiring:',
    },
    position: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 31,
      scriptVariable: 'Position',
    },
    location: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 37,
      scriptVariable: 'Location',
    },
    lineOne: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 1',
    },
    lineTwo: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 2',
    },
    lineThree: {
      type: 'data',
      fieldType: 'textArea',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 3',
    },
    lineFour: {
      type: 'data',
      fieldType: 'textArea',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 1',
    },
    lineFive: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 2',
    },
    lineSix: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 3',
    },
    lineSeven: {
      type: 'data',
      fieldType: 'textArea',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 1',
    },
    lineEight: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 2',
    },
    lineNine: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 3',
    },
    titleTwo: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 17,
      scriptVariable: 'Slide Title',
    },
    titleThree: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 17,
      scriptVariable: 'Slide Title',
    },
    titleFour: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 17,
      scriptVariable: 'Slide Title',
    },
    testimonial: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      lineLength: 18,
      maxLength: 54,
      scriptVariable: 'Testimonial Quote',
    },
    attribution: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 22,
      scriptVariable: 'Testimonial Attribution',
    },
    callToAction: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 9,
      scriptVariable: 'Call to Action',
      value: 'Apply Now',
    },
    colorImages: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 5,
      scriptVariable: 'Color Images (true/false)',
      value: 'false',
    },
  },
  globals: [
    'soundTrack',
    'brandColor1',
    'brandColor2',
    'brandColor3',
    'brandColor4',
    'logo',
    'iconOne',
    'iconTwo',
    'colorImages',
  ],
  slides: [
    ['backgroundImageOne', 'tagLine', 'position', 'location'],
    ['backgroundImageTwo', 'titleTwo', 'lineOne', 'lineTwo', 'lineThree'],
    ['backgroundImageThree', 'titleThree', 'lineFour', 'lineFive', 'lineSix'],
    ['backgroundImageFour', 'titleFour', 'lineSeven', 'lineEight', 'lineNine'],
    ['backgroundImageFive', 'testimonial', 'attribution'],
    ['callToAction'],
  ],
}
