import { Flavor } from './Flavor'

import path from 'path'

export const T10: Flavor = {
  name: 'Honey',
  meta: {
    description:
      'This :45 second template ensures every detail is covered, from mission statement to employee testimonial.',
    orientation: '16:9',
    duration: 45,
    imageUrl:
      'https://res.cloudinary.com/hdngr/image/upload/v1647965386/thumbnails/1758.jpg',
    vimeoId: '690704310',
    category: 'Job Postings',
  },
  template: {
    src: `file://${path.join(__dirname, '../../render-templates/T10/T10.aep')}`,
    composition: 'Main',
    outputExt: 'mov',
  },
  layers: {
    soundTrack: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Soundtrack',
    },
    brandColor1: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for main brand color elements.',
      scriptVariable: 'Color 1 (Banners slide 1 / contrast 2 & 3)',
    },
    brandColor2: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for text backgrounds and some headings',
      scriptVariable: 'Color 2 (Background slide 1 / contrast 1 & 3)',
    },
    brandColor3: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for text color.',
      scriptVariable: 'Color 3 (Text slide 1 / contrast 2 & 3)',
    },
    logo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Logo',
    },
    locationIcon: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Location Icon',
      id: '220',
    },
    backgroundImageOne: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 2 Image (far left)',
    },
    backgroundImageTwo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 3 Image (far left)',
    },
    backgroundImageThree: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 4 Image (far left)',
    },
    backgroundImageFour: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 5 Image (far left)',
    },
    coverImage: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 1 Cover Image',
    },
    tagline: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 11,
      scriptVariable: 'Tagline',
      value: "We're Hiring:",
    },
    position: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 16,
      scriptVariable: 'Position',
    },
    location: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 16,
      scriptVariable: 'Location',
    },
    slideTwoTitle: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 14,
      scriptVariable: 'Title for slide 2',
    },
    slideTwoBody: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 21,
      maxLength: 63,
      scriptVariable: 'Slide 2 Body',
    },
    slideThreeTitle: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 15,
      scriptVariable: 'Title for slide 3',
    },
    bulletOne: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 21,
      maxLength: 42,
      scriptVariable: 'Bullet 1',
    },
    bulletTwo: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 21,
      maxLength: 42,
      scriptVariable: 'Bullet 2',
    },
    bulletThree: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 21,
      maxLength: 42,
      scriptVariable: 'Bullet 3',
    },
    slideFourTitle: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 15,
      scriptVariable: 'Title for slide 4',
    },
    bulletFour: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 21,
      maxLength: 42,
      scriptVariable: 'Bullet 1',
    },
    bulletFive: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 21,
      maxLength: 42,
      scriptVariable: 'Bullet 2',
    },
    bulletSix: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 21,
      maxLength: 42,
      scriptVariable: 'Bullet 3',
    },
    slideFiveTitle: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 15,
      scriptVariable: 'Title for slide 5',
    },
    bulletSeven: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 21,
      maxLength: 42,
      scriptVariable: 'Bullet 1',
    },
    bulletEight: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 21,
      maxLength: 42,
      scriptVariable: 'Bullet 2',
    },
    bulletNine: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 21,
      maxLength: 42,
      scriptVariable: 'Bullet 3',
    },
    testimonial: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 26,
      maxLength: 52,
      scriptVariable: 'Testimonial',
    },
    attribution: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 32,
      scriptVariable: 'Attribution',
    },
  },
  globals: [
    'soundTrack',
    'brandColor1',
    'brandColor2',
    'brandColor3',
    'logo',
    'locationIcon',
  ],
  slides: [
    ['tagline', 'position', 'location', 'coverImage'],
    ['backgroundImageOne', 'slideTwoTitle', 'slideTwoBody'],
    [
      'backgroundImageTwo',
      'slideThreeTitle',
      'bulletOne',
      'bulletTwo',
      'bulletThree',
    ],
    [
      'backgroundImageThree',
      'slideFourTitle',
      'bulletFour',
      'bulletFive',
      'bulletSix',
    ],
    [
      'backgroundImageFour',
      'slideFiveTitle',
      'bulletSeven',
      'bulletEight',
      'bulletNine',
    ],
    ['testimonial', 'attribution'],
  ],
}
