import { Flavor } from './Flavor'

import path from 'path'

export const T11: Flavor = {
  name: 'Cotton Candy',
  meta: {
    description:
      'This template allows for multiple "paragraph style" frames to weave a narrative about the role.',
    orientation: '16:9',
    duration: 32,
    imageUrl:
      'https://res.cloudinary.com/hdngr/image/upload/v1649462783/thumbnails/1862.jpg',
    vimeoId: '697186853',
    category: 'Job Postings',
  },
  template: {
    src: `file://${path.join(__dirname, '../../render-templates/T11.aep')}`,
    composition: 'Main',
    outputExt: 'mov',
  },
  layers: {
    soundTrack: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Soundtrack',
    },
    brandColor1: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for main color elements.',
      scriptVariable: 'Banners & Bullets',
    },
    brandColor2: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for location icon.',
      scriptVariable: 'Location Icon Color',
    },
    textColor1: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for text over background color.',
      scriptVariable: 'Text over Background Color',
    },
    textColor2: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for headings and contact info.',
      scriptVariable: 'Text over Banner Color',
    },
    backgroundColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Background color.',
      scriptVariable: 'Background Color',
      value: '#ffffff',
    },
    logo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Logo',
    },
    iconLogo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Icon Only Logo',
    },
    locationIcon: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Location Icon',
      id: '220',
    },
    bulletIcon: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Bullet Icon',
      id: '204',
    },
    backgroundImageOne: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 1 Image (far right)',
    },
    backgroundImageTwo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 2 Image (far right)',
    },
    backgroundImageThree: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 3 Image (horizontal middle 40%)',
    },
    backgroundImageFour: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 4 Image (horizontal top 40%)',
    },
    backgroundImageFive: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 5 Image (far right)',
    },
    tagline: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 23,
      scriptVariable: 'Tagline',
    },
    position: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 57,
      scriptVariable: 'Position',
    },
    location: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 27,
      scriptVariable: 'Location',
    },
    slideTwoTitle: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 35,
      scriptVariable: 'Title for slide 2',
    },
    bulletOne: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 19,
      maxLength: 38,
      scriptVariable: 'Bullet 1',
    },
    bulletTwo: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 19,
      maxLength: 38,
      scriptVariable: 'Bullet 2',
    },
    bulletThree: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 19,
      maxLength: 38,
      scriptVariable: 'Bullet 3',
    },
    slideThreeTitle: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 35,
      scriptVariable: 'Title for slide 3',
    },
    slideThreeBody: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 49,
      maxLength: 98,
      scriptVariable: 'Slide 3 Body',
    },
    slideFourTitle: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 37,
      scriptVariable: 'Title for slide 4',
    },
    slideFourBody: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 50,
      maxLength: 100,
      scriptVariable: 'Slide 4 Body',
    },
    name: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 14,
      scriptVariable: 'Slide 5 Title (Name)',
    },
    email: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 29,
      scriptVariable: 'Email Address',
    },
    phone: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 25,
      scriptVariable: 'Phone Number',
    },
    showContact: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 5,
      scriptVariable: 'Show Contact (true/false)',
      value: 'true',
    },
  },
  globals: [
    'soundTrack',
    'brandColor1',
    'brandColor2',
    'textColor1',
    'textColor2',
    'backgroundColor',
    'logo',
    'iconLogo',
    'locationIcon',
    'bulletIcon',
    'showContact',
  ],
  slides: [
    ['backgroundImageOne', 'tagline', 'position', 'location'],
    [
      'backgroundImageTwo',
      'slideTwoTitle',
      'bulletOne',
      'bulletTwo',
      'bulletThree',
    ],
    ['backgroundImageThree', 'slideThreeTitle', 'slideThreeBody'],
    ['backgroundImageFour', 'slideFourTitle', 'slideFourBody'],
    ['backgroundImageFive', 'name', 'email', 'phone'],
  ],
}
