import { Flavor } from './Flavor'

import path from 'path'

export const T12: Flavor = {
  name: 'Pineapple',
  meta: {
    description:
      'Short and sweet - this template highlights the role and the recruiter.',
    orientation: '16:9',
    duration: 12,
    imageUrl:
      'https://res.cloudinary.com/hdngr/image/upload/v1649430476/thumbnails/1863.jpg',
    vimeoId: '697187979',
    category: 'Job Postings',
  },
  template: {
    src: `file://${path.join(__dirname, '../../render-templates/T12.aep')}`,
    composition: 'Main',
    outputExt: 'mov',
  },
  layers: {
    soundTrack: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Soundtrack',
    },
    soundEffect1: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Sound effect 1 - bloop',
      id: '3102',
    },
    soundEffect2: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Sound effect 2 - whoosh',
      id: '3104',
    },
    soundEffect3: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Sound effect 3 - keyboard',
      id: '3103',
    },
    bgColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Background color for slides.',
      scriptVariable: 'Background Color',
      value: '#ffffff',
    },
    primaryTextColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for tag line and job position text.',
      scriptVariable: 'Job title and tag line',
    },
    secondaryTextColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for recruiter name, call to action, email, and phone.',
      scriptVariable: 'Name, Email, Phone, CTA',
    },
    brandColor1: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Main Bubbles',
      scriptVariable: 'Main bubbles',
    },
    brandColor2: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Secondary bubbles.',
      scriptVariable: 'Secondary bubbles',
    },
    brandColor3: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Lined bubbles.',
      scriptVariable: 'Lined bubbles',
    },
    logo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Logo',
    },
    iconEmail: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Email Icon',
      id: '3106',
    },
    iconPhone: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Phone Icon',
      id: '3101',
    },
    tagLine: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 11,
      scriptVariable: 'We’re Hiring!',
      value: 'We’re Hiring!',
    },
    position: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 24,
      scriptVariable: 'Position',
    },
    callToAction: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 26,
      scriptVariable: 'Call to Action',
      value: 'Apply Now',
    },
    headshot: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Square head shot',
    },
    nameAndTitle: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 30,
      scriptVariable: 'Name and Title',
    },
    phone: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 16,
      scriptVariable: 'Phone number',
    },
    email: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 30,
      scriptVariable: 'Email',
    },
  },
  globals: [
    'soundTrack',
    'soundEffect1',
    'soundEffect2',
    'soundEffect3',
    'logo',
    'bgColor',
    'primaryTextColor',
    'secondaryTextColor',
    'brandColor1',
    'brandColor2',
    'brandColor3',
  ],
  slides: [
    ['tagLine', 'position', 'callToAction'],
    ['headshot', 'nameAndTitle', 'phone', 'email', 'iconEmail', 'iconPhone'],
  ],
}
