import { Flavor } from './Flavor'

import path from 'path'

export const T16: Flavor = {
  name: 'Cherry',
  meta: {
    description:
      'This fluid, light-hearted template highlights the core elements of the role',
    orientation: '16:9',
    duration: 32,
    imageUrl:
      'https://res.cloudinary.com/hdngr/image/upload/v1669082077/thumbnails/3499.jpg',
    vimeoId: '773596211',
    category: 'Job Postings',
  },
  template: {
    src: `file://${path.join(__dirname, '../../render-templates/T16.aep')}`,
    composition: 'Main',
    outputExt: 'mov',
  },
  layers: {
    soundTrack: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'soundtrack',
    },
    primaryTextColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Primary Text Color',
      scriptVariable: 'Primary Text Color',
    },
    backgroundColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Background Color, Cover Slide and CTA',
      scriptVariable: 'Background Color, Cover Slide and CTA Background',
    },
    brandColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Brand Color, Cover Slide and CTA Text Color',
      scriptVariable: 'Brand Color, Cover Slide Text Color',
    },
    logo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Logo',
    },
    coverPhoto: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Cover Photo 50% right',
    },
    slideTwoPhoto: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide Two Photo 50% right',
    },
    slideThreePhoto: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide Three Photo 50% left',
    },
    slideFourPhoto: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide Four Photo 50% left',
    },
    slideFivePhoto: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide Five Photo 50% right',
    },
    slideSixPhoto: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide Five Photo 50% right',
    },
    tagline: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 15,
      scriptVariable: 'Tagline',
      value: "We're Hiring!",
    },
    position: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 27,
      scriptVariable: 'Job Position',
    },
    location: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 13,
      scriptVariable: 'Job Location',
    },
    locationTitle: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 14,
      scriptVariable: 'Job Location Title',
      value: 'Located In',
    },
    slideThreeTitle: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 16,
      scriptVariable: 'Slide Three Title',
    },
    slideThreeText: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      maxLength: 72,
      scriptVariable: 'Slide Three Text',
    },
    slideFourTitle: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 18,
      scriptVariable: 'Bullet Points Title',
    },
    testimonialTitle: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 13,
      scriptVariable: 'Testimonial Title Text',
      value: 'Testimonial',
    },
    testimonial: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      maxLength: 57,
      scriptVariable: 'Testimonial Text',
    },
    attribution: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 21,
      scriptVariable: 'Testimonial Attribution',
      value: '-Employee Review',
    },
    bulletPointOne: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      maxLength: 36,
      lineLength: 18,
      scriptVariable: '1st bullet point',
    },
    bulletPointTwo: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      maxLength: 36,
      lineLength: 18,
      scriptVariable: '2nd bullet point',
    },
    bulletPointThree: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      maxLength: 36,
      lineLength: 18,
      scriptVariable: '3rd bullet point',
    },
    callToAction: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 17,
      scriptVariable: 'Call to action',
    },
  },
  globals: [
    'soundTrack',
    'logo',
    'backgroundColor',
    'brandColor',
    'primaryTextColor',
  ],
  slides: [
    ['tagline', 'position', 'coverPhoto'],
    ['location', 'slideTwoPhoto', 'locationTitle'],
    ['slideThreeTitle', 'slideThreeText', 'slideThreePhoto'],
    [
      'slideFourTitle',
      'bulletPointOne',
      'bulletPointTwo',
      'bulletPointThree',
      'slideFourPhoto',
    ],
    ['testimonialTitle', 'testimonial', 'attribution', 'slideFivePhoto'],
    ['callToAction', 'slideSixPhoto'],
  ],
}
