import { Flavor } from './Flavor'

import path from 'path'

export const T4: Flavor = {
  name: 'Bamboo',
  meta: {
    description:
      'The perfect template for when you want to focus on 1 or 2 key details.',
    orientation: '16:9',
    duration: 26,
    imageUrl:
      'https://res.cloudinary.com/hdngr/image/upload/v1654195185/thumbnails/1856.jpg',
    vimeoId: '697167318',
    category: 'Job Postings',
  },
  template: {
    src: `file://${path.join(__dirname, '../../render-templates/T4.aep')}`,
    composition: 'Main',
    outputExt: 'mov',
  },
  layers: {
    soundTrack: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Soundtrack',
    },
    bgColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Background color for slides.',
      scriptVariable: 'Background Color',
      value: '#ffffff',
    },
    primaryTextColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for titles and the main text on a slide.',
      scriptVariable:
        'Secondary Text (We’re Hiring, Location, Slide Headers, Apply Now)',
    },
    secondaryTextColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description:
        'Used for sub titles and secondary text on a slide (hint: can be the same as any of the other colors if you want!).',
      scriptVariable: 'Main Text (slide content)',
    },
    buttonTextColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for call to action text.',
      scriptVariable: 'Button Text (Apply Now)',
      value: '#ffffff',
    },
    utilColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'used for buttons and icons.',
      scriptVariable: 'Bullet and Icon color (slide header background)',
    },
    logo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Logo',
    },
    tagLine: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 17,
      scriptVariable: 'We’re Hiring!',
      value: 'We’re Hiring!',
    },
    position: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 20,
      scriptVariable: 'Position',
    },
    location: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 20,
      scriptVariable: 'Location',
    },
    iconOne: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Location Icon',
      id: '220',
    },
    iconTwo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Bullet Icon',
      id: '204',
    },
    backgroundImageOne: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Super Right',
    },
    lineOne: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 22,
      maxLength: 44,
      scriptVariable: 'Bullet 1',
    },
    lineTwo: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 22,
      maxLength: 44,
      scriptVariable: 'Bullet 2',
    },
    lineThree: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 22,
      maxLength: 44,
      scriptVariable: 'Bullet 3',
    },
    backgroundImageTwo: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Super Left',
    },
    lineFour: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 22,
      maxLength: 44,
      scriptVariable: 'Bullet 1',
    },
    lineFive: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 22,
      maxLength: 44,
      scriptVariable: 'Bullet 2',
    },
    lineSix: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 22,
      maxLength: 44,
      scriptVariable: 'Bullet 3',
    },
    backgroundImageThree: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Super Right',
    },
    testimonial: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 17,
      maxLength: 85,
      scriptVariable: 'Testimonial Quote',
    },
    testimonialName: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 19,
      scriptVariable: 'Testimonial Attribution',
    },
    callToAction: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 9,
      scriptVariable: 'Call to Action',
      value: 'Apply Now',
    },
  },
  globals: [
    'soundTrack',
    'logo',
    'bgColor',
    'primaryTextColor',
    'secondaryTextColor',
    'buttonTextColor',
    'utilColor',
    'iconOne',
    'iconTwo',
  ],
  slides: [
    ['tagLine', 'position', 'location'],
    ['backgroundImageOne', 'lineOne', 'lineTwo', 'lineThree'],
    ['backgroundImageTwo', 'lineFour', 'lineFive', 'lineSix'],
    ['backgroundImageThree', 'testimonial', 'testimonialName'],
    ['callToAction'],
  ],
}
