import { Flavor } from './Flavor'

import path from 'path'

export const T6: Flavor = {
  name: 'Lavender',
  meta: {
    description:
      'This template is a happy medium between brevity and detail - enough space to convey a compelling message while maintaining attention.',
    orientation: '16:9',
    duration: 30,
    imageUrl:
      'https://res.cloudinary.com/hdngr/image/upload/v1654195185/thumbnails/1859.jpg',
    vimeoId: '697174570',
    category: 'Job Postings',
  },
  template: {
    src: `file://${path.join(__dirname, '../../render-templates/T6.aep')}`,
    composition: 'Main',
    outputExt: 'mov',
  },
  layers: {
    soundTrack: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Soundtrack',
    },
    bgColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Background color for slides.',
      scriptVariable: 'Background Color',
      value: '#ffffff',
    },
    primaryTextColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for titles and the main text on a slide.',
      scriptVariable:
        'Secondary Text (We’re Hiring, Location, Slide Headers, Apply Now)',
    },
    buttonHeaderColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for titles with backgrounds and call to action text.',
      scriptVariable:
        'Button & Header Text (We’re Hiring, Location/Testimonial, Apply Now)',
      value: '#ffffff',
    },
    secondaryTextColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description:
        'Used for sub titles and secondary text on a slide (hint: can be the same as any of the other colors if you want!).',
      scriptVariable: 'Main Text (slide content)',
    },
    utilColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'used for buttons and icons.',
      scriptVariable: 'Bullet and Icon color (slide header background)',
    },
    logo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Logo',
    },
    tagLine: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 17,
      scriptVariable: 'We’re Hiring!',
      value: 'We’re Hiring!',
    },
    position: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 20,
      scriptVariable: 'Position',
    },
    location: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 20,
      scriptVariable: 'Location',
    },
    iconOne: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Location Icon',
      id: '220',
    },
    iconTwo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Bullet Icon',
      id: '204',
    },
    slideTwoBgImage: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Top 50%',
    },
    slideTwoTitle: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 15,
      scriptVariable: 'Slide Title',
    },
    slideTwoBody: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 120,
      lineLength: 40,
      scriptVariable: 'Content',
    },
    slideThreeBgImage: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Left 50%',
    },
    slideFiveBgImage: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Top 50%',
    },
    slideThreeTitle: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 16,
      scriptVariable: 'Slide Title',
    },
    lineOne: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 42,
      lineLength: 21,
      scriptVariable: 'Bullet 1',
    },
    lineTwo: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 42,
      lineLength: 21,
      scriptVariable: 'Bullet 2',
    },
    lineThree: {
      type: 'data',
      fieldType: 'textArea',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 42,
      lineLength: 21,
      scriptVariable: 'Bullet 3',
    },
    slideFourBgImage: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Right 50%',
    },
    slideFourTitle: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 16,
      scriptVariable: 'Slide Title',
    },
    lineFour: {
      type: 'data',
      fieldType: 'textArea',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 42,
      lineLength: 21,
      scriptVariable: 'Bullet 1',
    },
    lineFive: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 42,
      lineLength: 21,
      scriptVariable: 'Bullet 2',
    },
    lineSix: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 42,
      lineLength: 21,
      scriptVariable: 'Bullet 3',
    },
    slideFiveTitle: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 15,
      scriptVariable: 'Slide Title',
    },
    testimonial: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      lineLength: 29,
      maxLength: 58,
      scriptVariable: 'Testimonial Quote',
    },
    testimonialName: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 40,
      scriptVariable: 'Testimonial Attribution',
    },
    callToAction: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 20,
      scriptVariable: 'Call to Action',
      value: 'Apply Now',
    },
  },
  globals: [
    'soundTrack',
    'logo',
    'bgColor',
    'primaryTextColor',
    'secondaryTextColor',
    'buttonHeaderColor',
    'utilColor',
    'iconOne',
    'iconTwo',
  ],
  slides: [
    ['tagLine', 'position', 'location'],
    ['slideTwoBgImage', 'slideTwoTitle', 'slideTwoBody'],
    ['slideThreeBgImage', 'slideThreeTitle', 'lineOne', 'lineTwo', 'lineThree'],
    ['slideFourBgImage', 'slideFourTitle', 'lineFour', 'lineFive', 'lineSix'],
    ['slideFiveBgImage', 'slideFiveTitle', 'testimonial', 'testimonialName'],
    ['callToAction'],
  ],
}
