import { Flavor } from './Flavor'

import path from 'path'

export const T7: Flavor = {
  name: 'Fresh Cookies',
  meta: {
    description:
      'Short and sweet - this 10 second ad highlights employee testimonial quotes',
    orientation: '16:9',
    duration: 10,
    imageUrl:
      'https://res.cloudinary.com/hdngr/image/upload/v1649430672/thumbnails/1860.jpg',
    vimeoId: '697176272',
    category: 'Job Postings',
  },
  template: {
    src: `file://${path.join(__dirname, '../../render-templates/T7.aep')}`,
    composition: 'Main',
    outputExt: 'mov',
  },
  layers: {
    soundTrack: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Soundtrack',
    },
    bgColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Background color for slides.',
      scriptVariable: 'Background Color',
      value: '#ffffff',
    },
    primaryTextColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for job title and quote text.',
      scriptVariable: 'Job title and quote text',
    },
    secondaryTextColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for "Now Hiring", location, and attribution text.',
      scriptVariable: "We're Hiring, Location, & Attribution",
    },
    utilColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for highlight effect.',
      scriptVariable: 'Highlight color',
    },
    logo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Logo',
    },
    icon: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Location Icon',
      id: '220',
    },
    highlighterImage: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Highlighter Image',
      id: '2078',
    },
    tagLine: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 15,
      scriptVariable: 'We’re Hiring!',
      value: 'We’re Hiring!',
    },
    position: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 14,
      maxLength: 28,
      scriptVariable: 'Position',
    },
    location: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 20,
      scriptVariable: 'Location',
    },
    backgroundImageOne: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: '50% Left',
    },
    backgroundImageTwo: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: '50% Right',
    },
    quoteOne: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 19,
      maxLength: 57,
      scriptVariable: 'Quote 1',
    },
    attributionOne: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 30,
      scriptVariable: 'Attribution 1',
    },
    quoteTwo: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 19,
      maxLength: 57,
      scriptVariable: 'Quote 2',
    },
    attributionTwo: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 30,
      scriptVariable: 'Attribution 2',
    },
  },
  globals: [
    'soundTrack',
    'logo',
    'bgColor',
    'primaryTextColor',
    'secondaryTextColor',
    'utilColor',
    'icon',
    'highlighterImage',
  ],
  slides: [
    ['tagLine', 'position', 'location', 'backgroundImageOne'],
    [
      'backgroundImageTwo',
      'quoteOne',
      'attributionOne',
      'quoteTwo',
      'attributionTwo',
    ],
  ],
}
