import { Flavor } from './Flavor'

import path from 'path'

export const T8: Flavor = {
  name: 'Lemon Meringue',
  meta: {
    description:
      'Brand colors are the star of the show for this image-less template. Minimalist design allows your mission, benefits, and employee testimonial to stand out.',
    orientation: '16:9',
    duration: 32,
    imageUrl:
      'https://res.cloudinary.com/hdngr/image/upload/v1658459321/thumbnails/1861.jpg',
    vimeoId: '697177968',
    category: 'Job Postings',
  },
  template: {
    src: `file://${path.join(__dirname, '../../render-templates/T8/T8.aep')}`,
    composition: 'Main',
    outputExt: 'mov',
  },
  layers: {
    alternateTemplate: {
      type: 'select',
      fieldType: 'select',
      options: ['T8/T8.aep', 'T8/T8-short.aep'],
      scriptVariable: 'Alternate Template',
      value: 'T8/T8.aep',
    },
    soundTrack: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Soundtrack',
    },
    iconColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for highlight effect.',
      scriptVariable: 'Title/Border/Icon Color',
    },
    brandColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for pinwheel, bullet icons, & heading text.',
      scriptVariable: 'Wheel/Heading/Bullet Icon Color',
    },
    backgroundColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Background color, location icon, and tagline.',
      scriptVariable: 'Background/Tagline/Location Icon Color',
      value: '#ffffff',
    },
    primaryTextColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for mission text, testimonial, & bullets.',
      scriptVariable: 'Body Text Color',
    },
    logo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Logo',
    },
    locationIcon: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Location Icon',
      id: '220',
    },
    bulletIcon: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Bullet Icon',
      id: '2128',
    },
    slideTwoIcon: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 2 Icon (Mission)',
      id: '2119',
    },
    slideThreeIcon: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 3 Icon (Benefits)',
      id: '2116',
    },
    slideFourIcon: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 4 Icon (Quote)',
      id: '2123',
    },
    tagline: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 18,
      scriptVariable: 'We’re Hiring!',
      value: 'We’re Hiring!',
      slideType: 'top-arc-intro',
    },
    position: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 28,
      scriptVariable: 'Position',
    },
    location: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 26,
      scriptVariable: 'Location',
    },
    slideTwoTitle: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 18,
      scriptVariable: 'Title ("OUR MISSION")',
      value: 'OUR MISSION',
      slideType: 'right-arc-title',
    },
    slideTwoBody: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 25,
      maxLength: 75,
      scriptVariable: 'Body Text (Mission)',
    },
    slideThreeTitle: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 18,
      scriptVariable: 'Title ("BENEFITS")',
      value: 'BENEFITS',
      slideType: 'right-arc-bullets',
    },
    bulletOne: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 21,
      maxLength: 42,
      scriptVariable: 'Bullet 1',
    },
    bulletTwo: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 21,
      maxLength: 42,
      scriptVariable: 'Bullet 2',
    },
    bulletThree: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 21,
      maxLength: 42,
      scriptVariable: 'Bullet 3',
    },
    testimonial: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'textArea',
      lineLength: 24,
      maxLength: 72,
      scriptVariable: 'Testimonial',
      slideType: 'right-arc-testimonial',
    },
    attribution: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 23,
      scriptVariable: 'Attribution',
    },
    callToAction: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 15,
      scriptVariable: 'Call to Action',
      value: 'APPLY NOW',
      slideType: 'top-arc-cta',
    },
  },
  globals: [
    'soundTrack',
    'logo',
    'iconColor',
    'brandColor',
    'backgroundColor',
    'primaryTextColor',
    'locationIcon',
    'bulletIcon',
    'alternateTemplate',
  ],
  slides: [
    ['tagline', 'position', 'location'],
    ['slideTwoTitle', 'slideTwoBody', 'slideTwoIcon'],
    [
      'slideThreeTitle',
      'bulletOne',
      'bulletTwo',
      'bulletThree',
      'slideThreeIcon',
    ],
    ['testimonial', 'attribution', 'slideFourIcon'],
    ['callToAction'],
  ],
}
