-- AlterTable
ALTER TABLE "Script" ALTER COLUMN "layers" DROP DEFAULT,
ALTER COLUMN "globals" DROP DEFAULT,
ALTER COLUMN "slides" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Template" ALTER COLUMN "layers" DROP DEFAULT,
ALTER COLUMN "globals" DROP DEFAULT,
ALTER COLUMN "slides" DROP DEFAULT;
