import { TemplateFlavor } from '@lumina/api'
import { ScriptQuery } from '../src/Script'

export const T12: ScriptQuery = {
  id: 12,
  flavor: TemplateFlavor.T12,
  video: null,
  request: {
    customer: {
      id: 22,
    },
  },
  order: {
    id: 20,
  },
  layers: {
    soundTrack: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Soundtrack',
      id: '2771',
    },
    soundEffect1: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Sound effect 1 - bloop',
      id: '3102',
    },
    soundEffect2: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Sound effect 2 - whoosh',
      id: '3104',
    },
    soundEffect3: {
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Sound effect 3 - keyboard',
      id: '3103',
    },
    bgColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Background color for slides.',
      scriptVariable: 'Background Color',
      value: '#ffffff',
    },
    primaryTextColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for tag line and job position text.',
      scriptVariable: 'Job title and tag line',
      value: '#000000',
    },
    secondaryTextColor: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for recruiter name, call to action, email, and phone.',
      scriptVariable: 'Name, Email, Phone, CTA',
      value: '#0e6178',
    },
    brandColor1: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Main Bubbles',
      scriptVariable: 'Main bubbles',
      value: '#4223a8',
    },
    brandColor2: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Secondary bubbles.',
      scriptVariable: 'Secondary bubbles',
      value: '#070a55',
    },
    brandColor3: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Lined bubbles.',
      scriptVariable: 'Lined bubbles',
      value: '#ffb4fc',
    },
    logo: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Logo',
      id: '1062',
    },
    iconEmail: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Email Icon',
      id: '3106',
    },
    iconPhone: {
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Phone Icon',
      id: '3101',
    },
    tagLine: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 11,
      scriptVariable: 'We’re Hiring!',
      value: 'We’re Hiring!',
    },
    position: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 24,
      scriptVariable: 'Position',
      value: '000000000000000000000000',
    },
    callToAction: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 26,
      scriptVariable: 'Call to Action',
      value: 'Apply Now',
    },
    headshot: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Square head shot',
      id: '1537',
    },
    nameAndTitle: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 30,
      scriptVariable: 'Name and Title',
      value: '000000000000000000000000000000',
    },
    phone: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 16,
      scriptVariable: 'Phone number',
      value: '0000000000000000',
    },
    email: {
      type: 'data',
      property: 'Text.Source Text',
      composition: '_control',
      fieldType: 'text',
      maxLength: 30,
      scriptVariable: 'Email',
      value: '000000000000000000000000000000',
    },
  },
}
