import { TemplateFlavor } from '@lumina/api'
import { ScriptQuery } from '../src/Script'

export const T4: ScriptQuery = {
  id: 153,
  video: null,
  request: {
    customer: {
      id: 22,
    },
  },
  order: {
    id: 20,
  },
  layers: {
    logo: {
      id: '1002',
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Logo',
    },
    bgColor: {
      type: 'data',
      value: '#FFFFFF',
      property: 'Effects.Fill.Color',
      fieldType: 'color',
      composition: '_control',
      description: 'Background color for slides.',
      scriptVariable: 'Background Color',
    },
    iconOne: {
      id: '220',
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Location Icon',
    },
    iconTwo: {
      id: '204',
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Line Icon',
    },
    lineOne: {
      type: 'data',
      value: 'Give us your colors',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      scriptVariable: 'Req 1',
    },
    lineSix: {
      type: 'data',
      value: 'Tell your awesome story!',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      scriptVariable: 'Benefit Line 3',
    },
    lineTwo: {
      type: 'data',
      value: 'Pick some awesome images',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      scriptVariable: 'Req 2',
    },
    tagLine: {
      type: 'data',
      value: 'Next Level Recruiting For',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      scriptVariable: 'Tag Line',
    },
    lineFive: {
      type: 'data',
      value: 'Reach more candidates',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      scriptVariable: 'Benefit Line 2',
    },
    lineFour: {
      type: 'data',
      value: 'Beautiful, engaging video',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      scriptVariable: 'Benefit Line 1',
    },
    location: {
      type: 'data',
      value: 'Portland, OR',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      scriptVariable: 'Location',
    },
    position: {
      type: 'data',
      value: 'Your Next Hire',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      scriptVariable: 'Position',
    },
    lineThree: {
      type: 'data',
      value: "Don't forget a soundtrack",
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      scriptVariable: 'Req 3',
    },
    utilColor: {
      type: 'data',
      value: '#F4AC04',
      property: 'Effects.Fill.Color',
      fieldType: 'color',
      composition: '_control',
      description: 'used for buttons and icons.',
      scriptVariable: 'Icon and Button Color',
    },
    soundTrack: {
      id: '882',
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Sound Track',
    },
    testimonial: {
      type: 'data',
      value: '"Lumina videos are the bee\'s knees!"',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      scriptVariable: 'Testimonial',
    },
    callToAction: {
      type: 'data',
      value: 'Get In Touch!',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      scriptVariable: 'Call To Action',
    },
    testimonialName: {
      type: 'data',
      value: '- Brian F., CEO Lumina',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      scriptVariable: 'Testimonial Name',
    },
    primaryTextColor: {
      type: 'data',
      value: '#010144',
      property: 'Effects.Fill.Color',
      fieldType: 'color',
      composition: '_control',
      description: 'Used for titles and the main text on a slide.',
      scriptVariable: 'Primary Text Color',
    },
    slideTwoBgImage: {
      id: '737',
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 2 BG Image',
    },
    slideThreeBgImage: {
      id: '600',
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Slide 3 BG Image',
    },
    secondaryTextColor: {
      type: 'data',
      value: '#123456',
      property: 'Effects.Fill.Color',
      fieldType: 'color',
      composition: '_control',
      description:
        'Used for sub titles and secondary text on a slide (hint: can be the same as any of the other colors if you want!).',
      scriptVariable: 'Secondary Text Color',
    },
    backgroundImageThree: {
      id: '940',
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Testimonial BG Image',
    },
  },
  flavor: 'T4' as TemplateFlavor.T4,
}
