import { TemplateFlavor } from '@lumina/api'
import { ScriptQuery } from '../src/Script'

export const T2: ScriptQuery = {
  id: 235,
  flavor: TemplateFlavor.T2,
  video: null,
  request: {
    customer: {
      id: 22,
    },
  },
  order: {
    id: 20,
  },
  layers: {
    alternateTemplate: {
      type: 'select',
      fieldType: 'select',
      options: ['T2.aep', 'dispatch.aep', 'psd.aep',''],
      scriptVariable: 'Alternate Template',
      value: 'psd.aep',
    },
    logo: {
      id: '1006',
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Logo',
    },
    iconOne: {
      id: '220',
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Location Icon',
    },
    iconTwo: {
      id: '204',
      type: 'image',
      fieldType: 'image',
      scriptVariable: 'Bullet Icon',
    },
    soundTrack: {
      id: '1353',
      type: 'audio',
      fieldType: 'audio',
      scriptVariable: 'Sound Track',
    },
    brandColor1: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for titles and the main text on a slide.',
      scriptVariable: 'Brand Color (Contrast with background & button text)',
      value: '#090A3F',
    },
    brandColor2: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Background color for slides.',
      scriptVariable: 'Background Color',
      value: '#ffffff',
    },
    brandColor3: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description:
        'Used for sub titles and secondary text on a slide (hint: can be the same as any of the other colors if you want!).',
      scriptVariable: 'Main Text (slide content)',
      value: '#000000',
    },
    brandColor4: {
      type: 'data',
      property: 'Effects.Fill.Color',
      composition: '_control',
      fieldType: 'color',
      description: 'Used for titles with backgrounds and call to action text.',
      scriptVariable: 'Button & Contrast Text (Over Brand Color)',
      value: '#ffffff',
    },
    backgroundImageOne: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Under Job Title Banner',
      id: '759',
    },
    backgroundImageTwo: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Right 50%',
      id: '759',
    },
    backgroundImageThree: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Right 50%',
      id: '759',
    },
    backgroundImageFour: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Right 50%',
      id: '759',
    },
    backgroundImageFive: {
      fieldType: 'image',
      type: 'image',
      scriptVariable: 'Right 50%',
      id: '759',
    },
    tagLine: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 20,
      scriptVariable: 'Hiring: (Tagline)',
      value: '00000000000000000000',
    },
    position: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 31,
      scriptVariable: 'Position',
      value: '0000000000000000000000000000000',
    },
    location: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 37,
      scriptVariable: 'Location',
      value: '0000000000000000000000000000000000000',
    },
    lineOne: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 1',
      value: '0000000000000000000000 0000000000000000000000',
    },
    lineTwo: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 2',
      value: '0000000000000000000000 0000000000000000000000',
    },
    lineThree: {
      type: 'data',
      fieldType: 'textArea',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 3',
      value: '0000000000000000000000 0000000000000000000000',
    },
    lineFour: {
      type: 'data',
      fieldType: 'textArea',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 1',
      value: '0000000000000000000000 0000000000000000000000',
    },
    lineFive: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 2',
      value: '0000000000000000000000 0000000000000000000000',
    },
    lineSix: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 3',
      value: '0000000000000000000000 0000000000000000000000',
    },
    lineSeven: {
      type: 'data',
      fieldType: 'textArea',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 1',
      value: '0000000000000000000000 0000000000000000000000',
    },
    lineEight: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 2',
      value: '0000000000000000000000 0000000000000000000000',
    },
    lineNine: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      maxLength: 44,
      lineLength: 22,
      scriptVariable: 'Bullet 3',
      value: '0000000000000000000000 0000000000000000000000',
    },
    titleTwo: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 17,
      scriptVariable: 'Slide Title',
      value: '00000000000000000',
    },
    titleThree: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 17,
      scriptVariable: 'Slide Title',
      value: '00000000000000000',
    },
    titleFour: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 17,
      scriptVariable: 'Slide Title',
      value: '00000000000000000',
    },
    titleFive: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 16,
      scriptVariable: 'Slide Title',
      value: '0000000000000000',
    },
    bodyFive: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'textArea',
      composition: '_control',
      lineLength: 42,
      maxLength: 84,
      scriptVariable: 'Testimonial Quote',
      value: '000000000000000000000000000000000000000000000 000000000000000000000000000000000000000000000',
    },
    callToAction: {
      type: 'data',
      property: 'Text.Source Text',
      fieldType: 'text',
      composition: '_control',
      maxLength: 9,
      scriptVariable: 'Call to Action',
      value: '000000000',
    },
    colorImages: {
      type: 'data',
      fieldType: 'text',
      property: 'Text.Source Text',
      composition: '_control',
      maxLength: 5,
      scriptVariable: 'Color Images (true/false)',
      value: 'false',
    },
  },
}
